### ISSUE TITLE
Xcode8.1でドキュメントのビルドができない

### ISSUE THREAD

**Issue by ykomano** [KiiPlatform/IoTCloud-iOSSDK#248]
jazzy-options.jsで `"swift-version": "3",` と定義されているため
Xcode8.1ではSwift3.0.1なのでマッチしないためと思われる
`"swift-version": "3.0.1",` と変更したら動作した
Swift(Xcode)のバージョンによってjazzy-options.jsを書き換えなければいけないのでREADME.mdに書いておいたほうがいいと思います

```
$ swift --version
Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
```

**Comment by satoshikumano** [comment]
XCode8.2 (Swift 3.0.2) では変更の必要がないですね。

**Comment by ykomano** [comment]
$ swift --version
の値を取ってきているみたいなので結果を貼り付けてもらえますか?
8.2の環境がないので、Xode8.1と8.2で何が違うのか確認したいです
https://github.com/realm/jazzy/blob/master/lib/jazzy/sourcekitten.rb#L139
https://github.com/segiddins/xcinvoke/blob/master/lib/xcinvoke/xcode.rb#L109

**Comment by ykomano** [comment]
```
$ xcrun --version
xcrun version 30.
```

```
$ jazzy -v
jazzy version: 0.7.3
```

```
branchStr: develop
Git information : develop / 9697583
Command: jazzy -c --output docs --xcodebuild-arguments -project,../ThingIFSDK.xcodeproj,-scheme,ThingIFSDK --author Kii Corp --author_url http://kii.com --github_url https://github.com/KiiPlatform/thing-if-iOSSDK --swift-version 3 --exclude BlockObserver.swift,NSData+Operations.swift,OperationErrors.swift,BlockOperation.swift,NSLock+Operations.swift,OperationObserver.swift,DelayOperation.swift,NSOperation+Operations.swift,OperationQueue.swift,Dictionary+Operations.swift,NegatedCondition.swift,ReachabilityCondition.swift,ExclusivityController.swift,NoCancelledDependencies.swift,TimeoutObserver.swift,GroupOperation.swift,Operation.swift,URLSessionTaskOperation.swift,MutuallyExclusive.swift,OperationCondition.swift,IoTRequestOperation.swift,NSNumber+checkTypes.swift
/Users/ykomano/.anyenv/envs/rbenv/versions/2.0.0-p594/lib/ruby/gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten': Unable to find an Xcode with swift version 3. (RuntimeError)
        from /Users/ykomano/.anyenv/envs/rbenv/versions/2.0.0-p594/lib/ruby/gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:65:in `block in build'
        from /Users/ykomano/.anyenv/envs/rbenv/versions/2.0.0-p594/lib/ruby/gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:63:in `chdir'
        from /Users/ykomano/.anyenv/envs/rbenv/versions/2.0.0-p594/lib/ruby/gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:63:in `build'
        from /Users/ykomano/.anyenv/envs/rbenv/versions/2.0.0-p594/lib/ruby/gems/2.0.0/gems/jazzy-0.7.3/bin/jazzy:15:in `<top (required)>'
        from /Users/ykomano/.anyenv/envs/rbenv/versions/2.0.0-p594/bin/jazzy:23:in `load'
        from /Users/ykomano/.anyenv/envs/rbenv/versions/2.0.0-p594/bin/jazzy:23:in `<main>'
Command: zip -r ThingIFSDK-Documentation-develop-9697583.zip docs
        zip warning: name not matched: docs

zip error: Nothing to do! (try: zip -r ThingIFSDK-Documentation-develop-9697583.zip . -i docs)
```

**Comment by satoshikumano** [comment]
XCode 8.1では再現するようです。
古いバージョンのXCodeでの検証に時間をかけたくないので、クローズします。

# 結論
- XCode 8.2を使ってください。
- XCode 8.1を使う場合は、jazzy-options.jsに"swift-version": "3.0.1"を指定してください。
- テンポラリな情報なので、こちらのissueへの記載で対応完了とします。

**Comment by dairyo** [comment]
@satoshikumano @ykomano 
FYI

https://github.com/KiiPlatform/thing-if-iOSSDK/blob/develop/ThingIFSDK/Documentation/generateDocs.py#L55

この行で、swift-versionをjazzyコマンドに渡しています。XCode 8.1で、swift-versionを指定を消して実行したら、ドキュメントを作成できました。

今後も同じ問題が起こるなら、swift-versionの指定をやめるのもありかも。

**Comment by ykomano** [comment]
@shinsuke-nara 
ありがとうございます。
バージョンを固定することにあまり意味がないのであれば指定をしないのもありですね。
固定している場合バージョンが上がるたびにスクリプトも書き換えなければいけないので、指定をしないほうがメンテのコストも下がると思うので検討してみてください。

**Comment by ykomano** [comment]
READMEのRequirementsを更新してもらいました
https://github.com/KiiPlatform/thing-if-iOSSDK/commit/df50d8bd2c9ef83b3c861cee701fc423b4c45ed6
